spring.application.name=franchises
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/retopragma
spring.datasource.username=root
spring.datasource.password=
spring.docker.compose.enabled=true
#spring.docker.compose.lifecycle-management=none